# Name of the GitHub Action
name: Deploy New APK and Update JSON

# This action runs automatically whenever a new release is 'published'
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Give the job permission to write back to your repository

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Download the APK from the release using the CORRECT, WORKING action
      - name: Download release asset (app-release.apk)
        uses: cardinalby/download-release-asset-action@v1 # <-- This is the working action
        with:
          repo: ${{ github.repository }}
          version: ${{ github.ref_name }}
          file: app-release.apk
          output: "downloads/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Update apk-info.json with the new details
      - name: Update apk-info.json
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = './apk-info.json';
            const apkPath = './downloads/app-release.apk';
            
            const stats = fs.statSync(apkPath);
            const fileSizeInMB = (stats.size / (1024 * 1024)).toFixed(1);
            
            const version = "${{ github.ref_name }}".replace('v', '');
            const today = new Date().toISOString().slice(0, 10);
            
            const info = JSON.parse(fs.readFileSync(path, 'utf8'));
            
            info.version = version;
            info.update_date = today;
            info.size = `${fileSizeInMB} MB`;
            info.apk_url = `./downloads/app-release.apk`;
            
            fs.writeFileSync(path, JSON.stringify(info, null, 2));
            
            console.log(`Updated ${path} to version ${version}, size ${fileSizeInMB} MB`);

      # Step 4: Commit the updated files back to your repository
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update APK to version ${{ github.ref_name }}"
          file_pattern: "downloads/app-release.apk apk-info.json"
